// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFVmrmR-m0OwVFWxdeZX-2Q494jFTg3A0',
    appId: '1:842317772351:web:d975dfa130155ad60f2a8a',
    messagingSenderId: '842317772351',
    projectId: 'log-in-f762e',
    authDomain: 'log-in-f762e.firebaseapp.com',
    storageBucket: 'log-in-f762e.firebasestorage.app',
    measurementId: 'G-DHJE78VBV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKZXXNHgWeMjyjkBvWIRBMBMh1emXA6qg',
    appId: '1:842317772351:android:bf9554e311eb8f760f2a8a',
    messagingSenderId: '842317772351',
    projectId: 'log-in-f762e',
    storageBucket: 'log-in-f762e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUqKHYO-bYVNdUcbg5sLrCMUucIErCYJ4',
    appId: '1:842317772351:ios:f2329bc08405fc760f2a8a',
    messagingSenderId: '842317772351',
    projectId: 'log-in-f762e',
    storageBucket: 'log-in-f762e.firebasestorage.app',
    androidClientId: '842317772351-inrfqqeu219je5d0p0i8vq0uriu2ae0n.apps.googleusercontent.com',
    iosClientId: '842317772351-vli88iq7jpurmemu8bulif3j84sbrgt6.apps.googleusercontent.com',
    iosBundleId: 'com.example.completeMusicPlayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUqKHYO-bYVNdUcbg5sLrCMUucIErCYJ4',
    appId: '1:842317772351:ios:f2329bc08405fc760f2a8a',
    messagingSenderId: '842317772351',
    projectId: 'log-in-f762e',
    storageBucket: 'log-in-f762e.firebasestorage.app',
    androidClientId: '842317772351-inrfqqeu219je5d0p0i8vq0uriu2ae0n.apps.googleusercontent.com',
    iosClientId: '842317772351-vli88iq7jpurmemu8bulif3j84sbrgt6.apps.googleusercontent.com',
    iosBundleId: 'com.example.completeMusicPlayer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFVmrmR-m0OwVFWxdeZX-2Q494jFTg3A0',
    appId: '1:842317772351:web:953cf970f3fd7cae0f2a8a',
    messagingSenderId: '842317772351',
    projectId: 'log-in-f762e',
    authDomain: 'log-in-f762e.firebaseapp.com',
    storageBucket: 'log-in-f762e.firebasestorage.app',
    measurementId: 'G-Q2K24FMZHG',
  );
}
